# __version__ = "1.0"

#
# Shared variables
#

# __hostuser__ = "#{id -u}:#{id -g}"
# __common_cmd__ = ["cargo", "--version"]

#
# Actions
#

[rustc]
help = "Get version of rustc"
image = "clux/muslrust:stable"
command = ["rustc", "--version"]

[msg]
help = "Echo env var"
image = "alpine:3.11"
entrypoint = "sh"
command = ["-c", "echo ${HEADING} - ${MSG}"]

  [msg.envs]
  HEADING = "This is a header"
  MSG = "#{echo $MSG}"  # Comes from .doa.env

[color]
help = "Print colored text"
image = "alpine:3.11"
entrypoint = "sh"
command = ["-c", "echo -e 'This is \\e[91mRED\\e[39m!'"]

[user]
help = "Echo user"
image = "alpine:3.11"
entrypoint = "sh"
command = ["-c", "id -u"]
user = "#{id -u}:#{id -g}"

[not-yet-impl]
help = "Not yet implemented"
build = "./Dockerfile"
